### ISSUE TITLE
track.detach() not a function

### ISSUE THREAD

**Issue by smashingpixelsindia** [twilio/twilio-video.js#497]
Hi,

I am using twilio-video1.14.2 in React. I followed the quick start. Initially I was getting an error that said "track.attach() is not a function.

I changed:

```
attachTracks(tracks, container) {
	  tracks.forEach(function(track) {
	    container.appendChild(track.attach());
	  });
}

attachParticipantTracks(participant, container) {
	  var tracks = Array.from(participant.tracks.values());
	  this.attachTracks(tracks, container);
}

room.participants.forEach(function(participant) {
    log("Already in Room: '" + participant.identity + "'");
    var previewContainer = document.getElementById('remote-media');
    attachParticipantTracks(participant, previewContainer);
  });
```

to

```
participant.tracks.forEach(publication => {
  if (publication.isSubscribed) {
    console.log('publication is subscribed..');
    const track = publication.track;
    this.refs.remoteMedia.appendChild(track.attach());
   }
 });
participant.on('trackSubscribed', track => {
     this.refs.remoteMedia.appendChild(track.attach());
});
```

But now I get an error that says "track.detach() is not a function".

Here's the code where I detach the tracks:

```
participantDisconnected(participant) { 
     console.log(participant.tracks)
     participant.tracks.forEach(track => {
     const attachedElements = track.detach();
     attachedElements.forEach(element => element.remove());
  });	
}
room.on('participantConnected',this.participantConnected);
room.on('participantDisconnected', this.participantDisconnected);
```

Where do you think I am going wrong? I am really struggling with this for a few days for some reason. Request you to please assist me in setting up the video chat. I will be really grateful. Thank you!

**Comment by manjeshbhargav** [comment]
@smashingpixelsindia ,

Thanks for writing in with your issue. If you are using twilio-video.js@1.14.2, then `participant.tracks` is a collection of `RemoteTrack`s, which have the `attach` and `detach` methods. You should be able to use them as specified in the QuickStart.

From the errors that you are seeing, it looks like you are using twilio-vide.js@2.0.0-beta*, where `participant.tracks` is a collection of `RemoteTrackPublication`s. That is the reason you are not seeing  the `attach` and `detach` methods.

For twilio-video.js 2.x, the quickstart code can be found [here](https://github.com/twilio/video-quickstart-js/blob/master/quickstart/src/index.js). Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by freeboarder42** [comment]
@manjeshbhargav,

So, trackPublication.detach() is not available anymore and according to the quickstart trackPublication.track.detach() should work, but in Beta 5 a trackPublication does not have a track property? So how can I detach the HTML elements for the remote tracks?

**Comment by Govind13100** [comment]
@manjeshbhargav 

I still having these problem... firstly i using this version //media.twiliocdn.com/sdk/js/video/releases/1.14.0/twilio-video.js  and everthing working fine, but suddenly the remote video stopped showing without any error, the audio was working but remote video was not working. 

Then i tried https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta5/twilio-video.min.js this version 
it throw `track.attach() is not a function`. I also tried your updated [quickstart](https://github.com/twilio/video-quickstart-js/blob/master/quickstart/src/index.js) but still throws the same error  `track.attach() is not a function`

Can you please help out here, will be very appreciating

Thanks in advance

**Comment by freeboarder42** [comment]
@Govind13100 
I developed a video chat application that works with version 1.15 (using the new features) and also with 2.0.0-beta5 (which by the way seems to be pretty stable). When creating local tracks using `video.createLocalTracks`, these tracks have the `attach` method (because they are of type `LocalAudioTrack` or `LocalVideoTrack`). When handling the `Room` event `trackSubscribed`, the first parameter is either a `RemoteAudioTrack` or a `RemoteVideo` Track. These also have the attach method.

`attachParticipantTracks` looks a bit different in my case:

    attachParticipantTracks(participant, container, isLocal) {
       var tracks = this.getTracks(participant);
       this.attachTracks(tracks, container, isLocal);
    }

    getTracks(participant) {
       return Array.from(participant.tracks.values()).filter(function (publication) {
          return publication.track;
       }).map(function (publication) {
          return publication.track;
       });
    }

`getTracks` is the trick here. It reads the tracks from the track publications of the participant.

**Comment by Govind13100** [comment]
hi @freeboarder42 

Thanks for your answer that really helps. But now i am facing the detach() problem same as attach

do you have any solution for this ?

**Comment by freeboarder42** [comment]
Hi @Govind13100

Here is the relevant code:

    roomJoined(room) {
       ...
       room.on('participantDisconnected', this.onParticipantDisconnected);
       room.on('trackUnsubscribed', this.onParticipantUnpublishedTrack);
       ...
    }

    onParticipantDisconnected(participant, error) {
      // When a (remote) participant disconnects, detach the assiciated tracks
      this.detachParticipantTracks(participant);
    }
     
    onParticipantUnpublishedTrack(track, trackPublication) {
       this.detachTracks([track]);
    }

    detachParticipantTracks(participant) {
       var tracks = this.getTracks(participant);
       this.detachTracks(tracks);
    }

    detachTracks(tracks) {
       for (let track of tracks) {
         const htmlElements = track.detach();
         for (let htmlElement of htmlElements) {
            htmlElement.remove();
          }
       }
    }

Please note that `detachParticipantTracks` uses the `getTracks` function I put in my last post.

**Comment by charliebeesley** [comment]
@freeboarder42 Hi, thanks for your help above. 
When dealing with local tracks the updated getTracks function worked well, However when trying remote tracks it always returns null. I notice you are doing something with your isLocal variable. Are you able to share?

Thanks in adavnce

Charlie

**Comment by kaitlynbrown** [comment]
I'm seeing similar behaviour
It's weird - if I do `console.log(publication, publication.track)`, in the log, the publication will have a track property that is a non-null value, but then when it logs the track itself, it is null.

**Comment by smkrn110** [comment]
@Govind13100 

I had worked with v1.15 and currently v2.0.0-beta5 (successfully upgrade after reviewing the code of QuickStart app), can you put your code snippet so we could better figure out what is the issue.

**Comment by charliebeesley** [comment]
hi @kaitlynbrown 

We have managed to fix this by adding the following code in the room.on('participantConnected') function.


                    room.on('participantConnected', function (participant) {
                        $scope.log("Joining: '" + participant.identity + "'");

                        participant.tracks.forEach(publication => {
                            if (publication.isSubscribed) {
                                const track = publication.track;
                                document.getElementById('remote-media-div').appendChild(track.attach());
                            }
                        });

                        participant.on('trackSubscribed', function (track) {
                            document.getElementById('remote-media-div').appendChild(track.attach());
                        });
                    });

**Comment by 12MIT0020** [comment]
Hi @freeboarder42 

Thanks for giving solution for attach() is undefined issue.

**Comment by jadavpalak** [comment]
hi @freeboarder42 

getTracks() method works like charm.Thanks you for the solution.

**Comment by manjeshbhargav** [comment]
Hi @jadavpalak , @smashingpixelsindia ,

I'm going to close this issue since it looks like you got all the answers you needed. @freeboarder42 , thanks for helping out with providing code samples.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by douglasrcjames** [comment]
Following a demo on Twilio for React, then coming here to fix some of the outdated components from the comments, I am able to connect a local and remote track to Twilio, but am getting an error only when detaching of participant. Any ideas?

**Error is:**
```
TypeError: this.detachTracks is not a function
Room.onParticipantUnpublishedTrack
C:/Users/dougl/Documents/GitHub/react.minute.tech/src/components/questions/CallRoom.js:87
  84 | }
  85 | 
  86 | onParticipantUnpublishedTrack(track, trackPublication) {
> 87 | 	this.detachTracks([track]);
     | ^  88 | }
  89 | 
  90 | roomJoined(room) {

CallRoom.leaveRoom
C:/Users/dougl/Documents/GitHub/react.minute.tech/src/components/questions/CallRoom.js:43
  40 | }
  41 | 
  42 | leaveRoom() {
> 43 | 	this.state.activeRoom.disconnect();
     | ^  44 | 	this.setState({ hasJoinedRoom: false, localMediaAvailable: false });
  45 | }
  46 | 
```
**React component:**
```
import React, { Component } from 'react';
import Video from 'twilio-video';
import { withRouter } from "react-router-dom";

import { functions } from "../../Fire.js";

class CallRoom extends Component {
	constructor(props) {
		super(props);
		this.joinRoom = this.joinRoom.bind(this);
		this.leaveRoom = this.leaveRoom.bind(this);
		this.roomJoined = this.roomJoined.bind(this);
		this.detachTracks = this.detachTracks.bind(this);
		this.detachParticipantTracks =this.detachParticipantTracks.bind(this);

		this.state = {
			identity: null,
			roomName: '',
			roomNameErr: false, // Track error for room name TextField
			previewTracks: null,
			localMediaAvailable: false,
			hasJoinedRoom: false,
			activeRoom: '' // Track the current active room
		};
    }
	

	joinRoom() {
		console.log("Joining room '" + this.props.match.params.questionId + "'...");

		// grabToken call
		functions.httpsCallable('grabToken ')(this.props.user.uid).then((response) => {
			console.log(response.data.token)
			// Join the Room with the token from the server and the
			// LocalParticipant's Tracks.
			Video.connect(response.data.token, {name: this.props.match.params.questionId}).then(this.roomJoined, error => {
				console.error('Could not connect to Twilio: ' + error.code + " - " + error.message);
			});
		});
	}

	leaveRoom() {
		this.state.activeRoom.disconnect();
		this.setState({ hasJoinedRoom: false, localMediaAvailable: false });
	}

	getTracks(participant) {
		return Array.from(participant.tracks.values()).filter(function (publication) {
		   return publication.track;
		}).map(function (publication) {
		   return publication.track;
		});
	 }

	attachTracks(tracks, container) {
		tracks.forEach(track => {
			container.appendChild(track.attach());
		});
	}

	detachTracks(tracks) {
		for (let track of tracks) {
			const htmlElements = track.detach();
			for (let htmlElement of htmlElements) {
			   htmlElement.remove();
			 }
		  }
	  }

	// Attaches a track to a specified DOM container
	attachParticipantTracks(participant, container, isLocal) {
		var tracks = this.getTracks(participant);
		this.attachTracks(tracks, container, isLocal);
	 }
	
	detachParticipantTracks(participant) {
		var tracks = this.getTracks(participant);
		this.detachTracks(tracks);
	}

	onParticipantDisconnected(participant, error) {
		// When a (remote) participant disconnects, detach the associated tracks
		this.detachParticipantTracks(participant);
	}
	
	onParticipantUnpublishedTrack(track, trackPublication) {
		this.detachTracks([track]);
	}

	roomJoined(room) {
		// Called when a participant joins a room
		console.log("Joined as '" + this.props.user.uid + "'");
		this.setState({
			activeRoom: room,
			localMediaAvailable: true,
			hasJoinedRoom: true
		});

		// Attach LocalParticipant's Tracks, if not already attached.
		var previewContainer = this.refs.localMedia;
		if (!previewContainer.querySelector('video')) {
			this.attachParticipantTracks(room.localParticipant, previewContainer);
		}

		// Attach the Tracks of the room's participants.
		room.participants.forEach(participant => {
			console.log("Already in Room: '" + participant.identity + "'");
			var previewContainer = this.refs.remoteMedia;
			this.attachParticipantTracks(participant, previewContainer);
		});
	  
		// Participant joining room
		room.on('participantConnected', function (participant) {
			console.log("Joining: '" + participant.identity + "'");

			participant.tracks.forEach(publication => {
				if (publication.isSubscribed) {
					const track = publication.track;
					document.getElementById('remote-media').appendChild(track.attach());
				}
			});

			participant.on('trackSubscribed', function (track) {
				document.getElementById('remote-media').appendChild(track.attach());
			});
		});
	  
		// Attach participant’s tracks to DOM when they add a track
		room.on('trackAdded', (track, participant) => {
			console.log(participant.identity + ' added track: ' + track.kind);
			var previewContainer = this.refs.remoteMedia;
			this.attachTracks([track], previewContainer);
		});

		// Detach participant’s track from DOM when they remove a track.
		room.on('trackRemoved', (track, participant) => {
			console.log(participant.identity + ' removed track: ' + track.kind);
			this.detachTracks([track]);
		});
	
		room.on('participantDisconnected', this.onParticipantDisconnected);
		room.on('trackUnsubscribed', this.onParticipantUnpublishedTrack);
	
		// Once the local participant leaves the room, detach the Tracks
		// of all other participants, including that of the LocalParticipant.
		room.on('disconnected', () => {
			if (this.state.previewTracks) {
				this.state.previewTracks.forEach(track => {
					track.stop();
				});
			}
			this.detachParticipantTracks(room.localParticipant);
			room.participants.forEach(this.detachParticipantTracks);
			this.setState({
				activeRoom: null
			})
			this.setState({ hasJoinedRoom: false, localMediaAvailable: false });
		});
	}

	render() {
		// Only show video track after user has joined a room
		let showLocalTrack = this.state.localMediaAvailable ? (
			<div className="flex-item">
				<div ref="localMedia" />
			</div>
		) : '';
		// Hide 'Join Room' button if user has already joined a room.
		let joinOrLeaveRoomButton = this.state.hasJoinedRoom ? (
			<button className="s-btn-danger" onClick={this.leaveRoom}>Leave Room</button>
					) : (
                        <button className="s-btn" onClick={this.joinRoom}>Join Room</button>
					);
		return (	
            <div className="flex-container">
                {showLocalTrack}
                <div className="flex-item">
                    {joinOrLeaveRoomButton}
                </div>
                <div className="flex-item" ref="remoteMedia" id="remote-media" />
            </div>
		);
	}
}

export default withRouter(CallRoom);

```

**Comment by TravBradfield** [comment]
> Hi @Govind13100
> 
> Here is the relevant code:
> 
> ```
> roomJoined(room) {
>    ...
>    room.on('participantDisconnected', this.onParticipantDisconnected);
>    room.on('trackUnsubscribed', this.onParticipantUnpublishedTrack);
>    ...
> }
> 
> onParticipantDisconnected(participant, error) {
>   // When a (remote) participant disconnects, detach the assiciated tracks
>   this.detachParticipantTracks(participant);
> }
>  
> onParticipantUnpublishedTrack(track, trackPublication) {
>    this.detachTracks([track]);
> }
> 
> detachParticipantTracks(participant) {
>    var tracks = this.getTracks(participant);
>    this.detachTracks(tracks);
> }
> 
> detachTracks(tracks) {
>    for (let track of tracks) {
>      const htmlElements = track.detach();
>      for (let htmlElement of htmlElements) {
>         htmlElement.remove();
>       }
>    }
> }
> ```
> 
> Please note that `detachParticipantTracks` uses the `getTracks` function I put in my last post.

Hi @freeboarder42, 

Thanks for your help so far. I'm getting errors from the getTracks method. 

this.getTracks is not a function. (In 'this.getTracks(participant)', 'this.getTracks' is undefined)

I'm not sure why this is the case. If you have any ideas please let me know.

**Comment by corysimmons** [comment]
I got this `track.attach()`/`track.detach()` error even though local + remote video/audio seemed to be working fine.

I discovered it was because one of the tracks it was trying to `.attach()`/`.detach()` was the `data` track.

Just wrapping the attach/detach with `if (track.kind !== 'data') { ... }` fixed it for me. Hope this helps someone else.

**Comment by TravBradfield** [comment]
@corysimmons That's brilliant! Problem solved!! Thank you!!
